/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author USER
 */
public class frameUtama extends javax.swing.JFrame {

    /**
     * Creates new form frameUtama
     */
    public frameUtama() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFormUser = new javax.swing.JButton();
        btnTanggal = new javax.swing.JButton();
        btnFormHari = new javax.swing.JButton();
        btnDetailUser = new javax.swing.JButton();
        btnFormDetailPb = new javax.swing.JButton();
        btnFormData = new javax.swing.JButton();
        btnFormCatetan = new javax.swing.JButton();
        btnFormBulan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("MAIN MENU ABSENSI");

        btnFormUser.setBackground(new java.awt.Color(255, 204, 255));
        btnFormUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFormUser.setText("Form User");
        btnFormUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormUserActionPerformed(evt);
            }
        });

        btnTanggal.setBackground(new java.awt.Color(204, 255, 204));
        btnTanggal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTanggal.setText("Form Tanggal");
        btnTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanggalActionPerformed(evt);
            }
        });

        btnFormHari.setBackground(new java.awt.Color(255, 204, 204));
        btnFormHari.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFormHari.setText("Form Hari");
        btnFormHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormHariActionPerformed(evt);
            }
        });

        btnDetailUser.setBackground(new java.awt.Color(255, 255, 204));
        btnDetailUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDetailUser.setText("Form Detail User");
        btnDetailUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailUserActionPerformed(evt);
            }
        });

        btnFormDetailPb.setBackground(new java.awt.Color(204, 255, 204));
        btnFormDetailPb.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFormDetailPb.setText("Form Detail PB");
        btnFormDetailPb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormDetailPbActionPerformed(evt);
            }
        });

        btnFormData.setBackground(new java.awt.Color(255, 204, 255));
        btnFormData.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFormData.setText("Form Data");
        btnFormData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormDataActionPerformed(evt);
            }
        });

        btnFormCatetan.setBackground(new java.awt.Color(204, 204, 255));
        btnFormCatetan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFormCatetan.setText("Form Catetan");
        btnFormCatetan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormCatetanActionPerformed(evt);
            }
        });

        btnFormBulan.setBackground(new java.awt.Color(204, 204, 255));
        btnFormBulan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFormBulan.setText("Form Bulan");
        btnFormBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormBulanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnFormHari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormBulan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFormDetailPb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDetailUser, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(btnFormData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormCatetan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormUser)
                    .addComponent(btnFormDetailPb))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTanggal)
                    .addComponent(btnDetailUser))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormData)
                    .addComponent(btnFormHari))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormCatetan)
                    .addComponent(btnFormBulan))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanggalActionPerformed
        new frameTanggal().setVisible(true);
    }//GEN-LAST:event_btnTanggalActionPerformed

    private void btnFormUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormUserActionPerformed
        new frameUser().setVisible(true);
    }//GEN-LAST:event_btnFormUserActionPerformed

    private void btnFormHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormHariActionPerformed
        new frameHari().setVisible(true);
    }//GEN-LAST:event_btnFormHariActionPerformed

    private void btnDetailUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailUserActionPerformed
        new frameDetailUser().setVisible(true);
    }//GEN-LAST:event_btnDetailUserActionPerformed

    private void btnFormDetailPbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormDetailPbActionPerformed
        new frameDetailPb().setVisible(true);
    }//GEN-LAST:event_btnFormDetailPbActionPerformed

    private void btnFormDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormDataActionPerformed
        new frameData().setVisible(true);
    }//GEN-LAST:event_btnFormDataActionPerformed

    private void btnFormCatetanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormCatetanActionPerformed
        new frameCatetan().setVisible(true);
    }//GEN-LAST:event_btnFormCatetanActionPerformed

    private void btnFormBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormBulanActionPerformed
        new frameBulan().setVisible(true);
    }//GEN-LAST:event_btnFormBulanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetailUser;
    private javax.swing.JButton btnFormBulan;
    private javax.swing.JButton btnFormCatetan;
    private javax.swing.JButton btnFormData;
    private javax.swing.JButton btnFormDetailPb;
    private javax.swing.JButton btnFormHari;
    private javax.swing.JButton btnFormUser;
    private javax.swing.JButton btnTanggal;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
